app:
  base-url: http://localhost:8080

spring:
  application:
    name: shortener

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/shortener
    username: app
    password: app

  sql:
    init:
      mode: always

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  logging:
    level: INFO